# -*- coding: utf-8 -*-
"""Sudoku_Net.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1WTwygQWz50DW6b0aVpws3V9Ka67m2dxa
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import time


class sudokunet1(nn.Module):
  def __init__(self,output_classes,in_channels = 1):
    super(sudokunet1,self).__init__()
    self.conv1 = nn.Conv2d(1,32,kernel_size = 5,stride = 1,padding = 1) #26x26
    self.pool1 = nn.MaxPool2d(2) #13x13
    self.conv2 = nn.Conv2d(32,32,kernel_size = 3, stride = 1,padding = 1) #13x13
    self.pool2 = nn.MaxPool2d(2) #6x6
    self.fc1 = nn.Linear(1152,128)
    self.dropout1 = nn.Dropout(p=0.2)
    self.fc2 = nn.Linear(128,64)
    self.output = nn.Linear(64, output_classes)

  def forward(self,x):
    x = self.conv1(x)
    x = F.relu(x)
    x = self.pool1(x)
    x = self.conv2(x)
    x = F.relu(x)
    x = self.pool2(x)
    x = x.reshape(x.shape[0],-1)
    x = self.fc1(x)
    x = F.relu(x)
    x = self.dropout1(x)
    x = self.fc2(x)
    x = F.relu(x)
    x = self.output(x)
    x = F.softmax(x)
    
    return x

#Output height = (Input height + padding height top + padding height bottom - kernel height) / (stride height) + 1

#Output width = (Output width + padding width right + padding width left - kernel width) / (stride width) + 1
class sudokunet2(nn.Module):
  def __init__(self,output_classes,in_channels = 1):
    super(sudokunet2,self).__init__()
    self.conv1 = nn.Conv2d(1,32,kernel_size = 5,stride = 1,padding = 1) #26x26
    self.pool1 = nn.MaxPool2d(2)#13x13
    self.conv2 = nn.Conv2d(32,64,kernel_size = 3, stride = 1,padding = 1) #13x13
    self.pool2 = nn.MaxPool2d(2) #6x6
    self.fc1 = nn.Linear(2304,128)
    self.dropout1 = nn.Dropout(p=0.2)
    self.fc2 = nn.Linear(128,64)
    self.dropout2 = nn.Dropout(p=0.4)
    self.output = nn.Linear(64, output_classes)

  def forward(self,x):
    x = self.conv1(x)
    x = F.relu(x)
    x = self.pool1(x)
    x = self.conv2(x)
    x = F.relu(x)
    x = self.pool2(x)
    x = x.reshape(x.shape[0],-1)
    x = self.fc1(x)
    x = F.relu(x)
    x = self.dropout1(x)
    x = self.fc2(x)
    x = F.relu(x)
    x = self.dropout2(x)
    x = self.output(x)
    x = F.softmax(x)
    
    return x
#Output height = (Input height + padding height top + padding height bottom - kernel height) / (stride height) + 1

#Output width = (Output width + padding width right + padding width left - kernel width) / (stride width) + 1
class sudokunet3(nn.Module):
  def __init__(self,output_classes,in_channels = 1):
    super(sudokunet3,self).__init__()
    self.conv1 = nn.Conv2d(1,32,kernel_size = 5,stride = 1,padding = 1) #26x26
    self.pool1 = nn.MaxPool2d(2)#13x13
    self.conv2 = nn.Conv2d(32,64,kernel_size = 3, stride = 1,padding = 1) #13x13
    self.pool2 = nn.MaxPool2d(2) #6x6
    self.fc1 = nn.Linear(2304,256)
    self.dropout1 = nn.Dropout(p=0.25)
    self.fc2 = nn.Linear(256,128)
    self.dropout2 = nn.Dropout(p=0.5)
    self.output = nn.Linear(128, output_classes)

  def forward(self,x):
    x = self.conv1(x)
    x = F.relu(x)
    x = self.pool1(x)
    x = self.conv2(x)
    x = F.relu(x)
    x = self.pool2(x)
    x = x.reshape(x.shape[0],-1)
    x = self.fc1(x)
    x = F.relu(x)
    x = self.dropout1(x)
    x = self.fc2(x)
    x = F.relu(x)
    x = self.dropout2(x)
    x = self.output(x)
    x = F.softmax(x)
    
    return x
  
def predict(model,x):
  device = torch.device("cuda")
  model.eval()
  model = model.to(device = device)
  with torch.no_grad():
    x.to(device)
    scores = model(x)
    prediction = scores.argmax(1)

  return prediction
